image: nokeedev/gcc-builder

build:
  stage: build
  script: ./gradlew assemble -PskipAllAsciinemaTasks --scan --continue
  artifacts:
    when: on_failure
    paths:
      - subprojects/*/build/

test (macos):
  stage: test
  # FIXME: Shouldn't need to ignore the Asciinema tasks, they should just not be wired in for testing
  script: ./gradlew check --scan --continue -PskipAllAsciinemaTasks
  variables:
    LANG: en_CA.UTF-8
  tags:
    - os=macos
  artifacts:
    when: on_failure
    paths:
      - subprojects/*/build

test (linux):
  stage: test
  # FIXME: Shouldn't need to ignore the Asciinema tasks, they should just not be wired in for testing
  script: ./gradlew check --scan --continue -PskipAllAsciinemaTasks
  tags:
    - os=linux
  artifacts:
    when: on_failure
    paths:
      - subprojects/*/build

# test (windows):
#   stage: test
#   # FIXME: Shouldn't need to ignore the Asciinema tasks, they should just not be wired in for testing
#   script: cmd.exe /c "gradlew.bat check --scan --continue -PskipAllAsciinemaTasks"
#   tags:
#     - os=windows
#   variables:
#     GIT_CLONE_PATH: $CI_BUILDS_DIR/gn
#     GRADLE_OPTS: "-Dorg.gradle.daemon=false"
#   artifacts:
#     when: on_failure
#     paths:
#       - subprojects/*/build

deploy:
  stage: build
  script: ./gradlew --scan :distributions:publishToBintray
  only:
    - master


publish (JBake Templates):
  stage: build
  script:
    - ./gradlew --scan :docs:publishJbakePublicationToS3Repository
    - curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=master https://gitlab.com/api/v4/projects/17545900/trigger/pipeline # docs.nokee.dev
    - curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=master https://gitlab.com/api/v4/projects/16537594/trigger/pipeline # nokeedev.gitlab.io
  only:
    changes:
      - .gitlab-ci.yml
      - subprojects/docs/src/jbake/**/*
      - subprojects/docs/docs.gradle
      - gradle/plugins/docs-gradle-plugin/**/*
    refs:
      - master
  artifacts:
    when: on_failure
    paths:
      - subprojects/docs/build/**/*

publish (docs nightly):
  stage: build
  script:
    - ./gradlew --scan --max-workers 4 --info :docs:bakedDocsTest :docs:publishBakedPublicationToS3Repository
    - curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=master https://gitlab.com/api/v4/projects/16537594/trigger/pipeline # nokeedev.gitlab.io
  tags:
    - container=baremetal
  only:
    refs:
      - master
  artifacts:
    when: on_failure
    paths:
      - subprojects/docs/build/**/*
