name: Contributor

on: push

jobs:
    assemble-without-secrets:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/setup-java@v1
                with:
                    java-version: '8'
            -   name: Build all code
                id: gradle
                uses: eskatos/gradle-command-action@v1
                with:
                    arguments: :platformJni:assemble --scan --continue --no-daemon
                    wrapper-cache-enabled: true
                    dependencies-cache-enabled: true
