name: CI

on: push

jobs:
    assemble:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/setup-java@v1
                with:
                    java-version: '8'
            -   name: Install documentation dependencies
                run: sudo apt-get update && sudo apt-get -y install graphviz asciinema imagemagick gifsicle ffmpeg tree && sudo npm --global install asciicast2gif giflossy --unsafe-perm
            -   name: Build all code
                id: gradle
                uses: eskatos/gradle-command-action@v1
                with:
                    arguments: assemble --scan --continue --no-daemon "-Ddev.nokee.gradle.cache.remote.username=${{ secrets.GRADLE_CACHE_USERNAME }}" "-Ddev.nokee.gradle.cache.remote.password=${{ secrets.GRADLE_CACHE_PASSWORD }}" -PskipAllAsciinemaTasks
                    wrapper-cache-enabled: true
                    dependencies-cache-enabled: true
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    CI: true
    deploy:
        needs: assemble
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/master'
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/setup-java@v1
                with:
                    java-version: '8'
            -   name: Deploy to snapshot
                id: gradle
                uses: eskatos/gradle-command-action@v1
                with:
                    arguments: :distributions:publishToBintray --scan --no-daemon "-Ddev.nokee.gradle.cache.remote.username=${{ secrets.GRADLE_CACHE_USERNAME }}" "-Ddev.nokee.gradle.cache.remote.password=${{ secrets.GRADLE_CACHE_PASSWORD }}"
                    wrapper-cache-enabled: true
                    dependencies-cache-enabled: true
                env:
                    BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
                    BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
                    CI: true
    windows:
        needs: assemble
        runs-on: windows-latest
        strategy:
            fail-fast: false
            matrix:
                checkTask: [':buildAdapterCmake:check', ':coreUtils:check', ':ideBase:check', ':ideVisualStudio:check', ':ideXcode:check', ':languageNative:check', ':platformBase:check', ':platformIos:check', ':platformJni:check', ':platformNative:check', ':runtimeBase:check', ':runtimeDarwin:check', ':runtimeNative:check', ':testingBase:check', ':testingNative:check', ':testingXctest:check']
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/setup-java@v1
                with:
                    java-version: '8'
            -   name: Run all tests
                id: gradle
                uses: eskatos/gradle-command-action@v1
                with:
                    arguments: ${{ matrix.checkTask }} --scan --continue --no-daemon "-Ddev.nokee.gradle.cache.remote.username=${{ secrets.GRADLE_CACHE_USERNAME }}" "-Ddev.nokee.gradle.cache.remote.password=${{ secrets.GRADLE_CACHE_PASSWORD }}"
                    wrapper-cache-enabled: true
                    dependencies-cache-enabled: true
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    CI: true

    macos:
        needs: assemble
        runs-on: macos-latest
        strategy:
            fail-fast: false
            matrix:
                checkTask: [':buildAdapterCmake:check', ':coreUtils:check', ':ideBase:check', ':ideVisualStudio:check', ':ideXcode:check', ':languageNative:check', ':platformBase:check', ':platformIos:check', ':platformJni:check', ':platformNative:check', ':runtimeBase:check', ':runtimeDarwin:check', ':runtimeNative:check', ':testingBase:check', ':testingNative:check', ':testingXctest:check']
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/setup-java@v1
                with:
                    java-version: '8'
            -   name: Run all tests
                id: gradle
                uses: eskatos/gradle-command-action@v1
                with:
                    arguments: ${{ matrix.checkTask }} --scan --continue --no-daemon "-Ddev.nokee.gradle.cache.remote.username=${{ secrets.GRADLE_CACHE_USERNAME }}" "-Ddev.nokee.gradle.cache.remote.password=${{ secrets.GRADLE_CACHE_PASSWORD }}"
                    wrapper-cache-enabled: true
                    dependencies-cache-enabled: true
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    CI: true

    linux:
        needs: assemble
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                checkTask: [':buildAdapterCmake:check', ':coreUtils:check', ':ideBase:check', ':ideVisualStudio:check', ':ideXcode:check', ':languageNative:check', ':platformBase:check', ':platformIos:check', ':platformJni:check', ':platformNative:check', ':runtimeBase:check', ':runtimeDarwin:check', ':runtimeNative:check', ':testingBase:check', ':testingNative:check', ':testingXctest:check']
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/setup-java@v1
                with:
                    java-version: '8'
            -   name: Install gobjc-8, gobjc++-8 and pthread
                run: sudo apt-get update && sudo apt-get -y install gobjc-8 gobjc++-8 gcc-8-multilib g++-8-multilib libpthread-stubs0-dev
            -   name: Run all tests
                id: gradle
                uses: eskatos/gradle-command-action@v1
                with:
                    arguments: ${{ matrix.checkTask }} --scan --continue --no-daemon "-Ddev.nokee.gradle.cache.remote.username=${{ secrets.GRADLE_CACHE_USERNAME }}" "-Ddev.nokee.gradle.cache.remote.password=${{ secrets.GRADLE_CACHE_PASSWORD }}"
                    wrapper-cache-enabled: true
                    dependencies-cache-enabled: true
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    CI: true
