name: CI

on: push

jobs:
    assemble:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/setup-java@v1
                with:
                    java-version: '8'
            -   name: Install documentation dependencies
                run: sudo apt-get update && sudo apt-get -y install graphviz asciinema imagemagick gifsicle ffmpeg tree && sudo npm --global install asciicast2gif giflossy --unsafe-perm
            -   name: Build all code
                id: gradle
                uses: eskatos/gradle-command-action@v1
                with:
                    arguments: assemble --scan --continue --no-daemon "-DnokeeBuildCacheUsername=${{ secrets.GRADLE_CACHE_USERNAME }}" "-DnokeeBuildCachePassword=${{ secrets.GRADLE_CACHE_PASSWORD }}" -PskipAllAsciinemaTasks
                    wrapper-cache-enabled: true
                    dependencies-cache-enabled: true
    deploy:
        needs: assemble
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/master'
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/setup-java@v1
                with:
                    java-version: '8'
            -   name: Deploy to snapshot
                id: gradle
                uses: eskatos/gradle-command-action@v1
                with:
                    arguments: publishAllPublicationsToNokeeSnapshotRepository --scan --no-daemon "-DnokeeBuildCacheUsername=${{ secrets.GRADLE_CACHE_USERNAME }}" "-DnokeeBuildCachePassword=${{ secrets.GRADLE_CACHE_PASSWORD }}" "-PnokeeSnapshotAccessKey=${{ secrets.NOKEE_SNAPSHOT_ACCESS_KEY }}" "-PnokeeSnapshotSecretKey=${{ secrets.NOKEE_SNAPSHOT_SECRET_KEY }}" "-PnokeeSnapshotUrl=${{ secrets.NOKEE_SNAPSHOT_URL }}"
                    wrapper-cache-enabled: true
                    dependencies-cache-enabled: true
    windows:
        needs: assemble
        runs-on: windows-latest
        strategy:
            fail-fast: false
            matrix:
                checkTask: [
                    ':buildAdapterCmake:check',
                    ':coreExec:check',
                    ':coreGradle:check',
                    ':coreModel:check',
                    ':coreScript:check',
                    ':coreUtils:check',
                    ':docs:exemplarKit:check',
                    ':experimentalPublishingBintray:check',
                    ':ideBase:check',
                    ':ideVisualStudio:check',
                    ':ideXcode:check',
                    ':internalTesting:check',
                    ':languageBase:check',
                    ':languageC:check',
                    ':languageCpp:check',
                    ':languageNative:check',
                    ':languageObjectiveC:check',
                    ':languageObjectiveCpp:check',
                    ':languageSwift:check',
                    ':platformBase:check',
                    ':platformIos:check',
                    ':platformJni:check',
                    ':platformNative:check',
                    ':runtimeBase:check',
                    ':runtimeDarwin:check',
                    ':runtimeNative:check',
                    ':runtimeWindows:check',
                    ':testingBase:check',
                    ':testingNative:check',
                    ':testingXctest:check']
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/setup-java@v1
                with:
                    java-version: '8'
            -   name: Run all tests
                id: gradle
                uses: eskatos/gradle-command-action@v1
                with:
                    arguments: ${{ matrix.checkTask }} --scan --continue --no-daemon "-DnokeeBuildCacheUsername=${{ secrets.GRADLE_CACHE_USERNAME }}" "-DnokeeBuildCachePassword=${{ secrets.GRADLE_CACHE_PASSWORD }}"
                    wrapper-cache-enabled: true
                    dependencies-cache-enabled: true

    macos:
        needs: assemble
        runs-on: macos-latest
        strategy:
            fail-fast: false
            matrix:
                checkTask: [
                    ':buildAdapterCmake:check',
                    ':coreExec:check',
                    ':coreGradle:check',
                    ':coreModel:check',
                    ':coreScript:check',
                    ':coreUtils:check',
                    ':docs:exemplarKit:check',
                    ':experimentalPublishingBintray:check',
                    ':ideBase:check',
                    ':ideVisualStudio:check',
                    ':ideXcode:check',
                    ':internalTesting:check',
                    ':languageBase:check',
                    ':languageC:check',
                    ':languageCpp:check',
                    ':languageNative:check',
                    ':languageObjectiveC:check',
                    ':languageObjectiveCpp:check',
                    ':languageSwift:check',
                    ':platformBase:check',
                    ':platformIos:check',
                    ':platformJni:check',
                    ':platformNative:check',
                    ':runtimeBase:check',
                    ':runtimeDarwin:check',
                    ':runtimeNative:check',
                    ':runtimeWindows:check',
                    ':testingBase:check',
                    ':testingNative:check',
                    ':testingXctest:check']
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/setup-java@v1
                with:
                    java-version: '8'
            -   name: Run all tests
                id: gradle
                uses: eskatos/gradle-command-action@v1
                with:
                    arguments: ${{ matrix.checkTask }} --scan --continue --no-daemon "-DnokeeBuildCacheUsername=${{ secrets.GRADLE_CACHE_USERNAME }}" "-DnokeeBuildCachePassword=${{ secrets.GRADLE_CACHE_PASSWORD }}"
                    wrapper-cache-enabled: true
                    dependencies-cache-enabled: true

    linux:
        needs: assemble
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                checkTask: [
                    ':buildAdapterCmake:check',
                    ':coreExec:check',
                    ':coreGradle:check',
                    ':coreModel:check',
                    ':coreScript:check',
                    ':coreUtils:check',
                    ':docs:exemplarKit:check',
                    ':experimentalPublishingBintray:check',
                    ':ideBase:check',
                    ':ideVisualStudio:check',
                    ':ideXcode:check',
                    ':internalTesting:check',
                    ':languageBase:check',
                    ':languageC:check',
                    ':languageCpp:check',
                    ':languageNative:check',
                    ':languageObjectiveC:check',
                    ':languageObjectiveCpp:check',
                    ':languageSwift:check',
                    ':platformBase:check',
                    ':platformIos:check',
                    ':platformJni:check',
                    ':platformNative:check',
                    ':runtimeBase:check',
                    ':runtimeDarwin:check',
                    ':runtimeNative:check',
                    ':runtimeWindows:check',
                    ':testingBase:check',
                    ':testingNative:check',
                    ':testingXctest:check']
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/setup-java@v1
                with:
                    java-version: '8'
            -   name: Install gcc dependencies
                run: sudo apt-get update && sudo apt-get -y install gobjc-8-multilib gobjc++-8-multilib gcc-8-multilib g++-8-multilib gobjc-9-multilib gobjc++-9-multilib gcc-9-multilib g++-9-multilib libpthread-stubs0-dev
            -   name: Run all tests
                id: gradle
                uses: eskatos/gradle-command-action@v1
                with:
                    arguments: ${{ matrix.checkTask }} --scan --continue --no-daemon "-DnokeeBuildCacheUsername=${{ secrets.GRADLE_CACHE_USERNAME }}" "-DnokeeBuildCachePassword=${{ secrets.GRADLE_CACHE_PASSWORD }}"
                    wrapper-cache-enabled: true
                    dependencies-cache-enabled: true
